name: Daily Activity Update

on:
  schedule:
    - cron: '5 0 * * *'  # Runs at 00:05 UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Update activity data
        run: python .github/scripts/update_activity.py
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add src/data/activityData.ts
          git commit -m "Add activity placeholder for $(date +'%Y-%m-%d')"
          git push